const PROPERTIES = [
  // Mumbai - Flat (25 properties)
  {
    id: 1,
    city: "Mumbai",
    area: "Bandra",
    address: "101 Sunrise Plaza, Linking Road, Bandra West, Mumbai 400050",
    propertyType: "flat",
    size: "2BHK",
    price: 25000,
    amenities: ["swimming pool", "lift", "gym", "parking"],
    photos: [],
    rating: 4.5,
    reviews: 12,
    owner: "Raj Kumar",
    contact: "+91-9876543210",
    nearbyPlaces: { hospital: 0.5, school: 0.8, airport: 15, mall: 1.2, railwayStation: 2, metroStation: 0.5 }
  },
  {
    id: 2,
    city: "Mumbai",
    area: "Andheri",
    address: "205 Green Heights, SV Road, Andheri West, Mumbai 400058",
    propertyType: "flat",
    size: "1BHK",
    price: 15000,
    amenities: ["lift", "parking", "water storage"],
    photos: [],
    rating: 4.0,
    reviews: 8,
    owner: "Priya Singh",
    contact: "+91-9876543211",
    nearbyPlaces: { hospital: 0.7, school: 0.6, airport: 10, mall: 1.5, railwayStation: 1.2, metroStation: 0.3 }
  },
  {
    id: 3,
    city: "Mumbai",
    area: "Powai",
    address: "312 Crystal Towers, Powai Road, Powai, Mumbai 400076",
    propertyType: "flat",
    size: "3BHK",
    price: 35000,
    amenities: ["swimming pool", "gym", "lift", "parking", "security"],
    photos: [],
    rating: 4.7,
    reviews: 25,
    owner: "Amit Sharma",
    contact: "+91-9876543212",
    nearbyPlaces: { hospital: 1.0, school: 0.9, airport: 18, mall: 0.8, railwayStation: 3, metroStation: 1.2 }
  },
  {
    id: 4,
    city: "Mumbai",
    area: "Dadar",
    address: "404 Elite Residency, Dadar East, Mumbai 400014",
    propertyType: "flat",
    size: "2BHK",
    price: 22000,
    amenities: ["lift", "parking", "security"],
    photos: [],
    rating: 3.8,
    reviews: 6,
    owner: "Neha Patel",
    contact: "+91-9876543213",
    nearbyPlaces: { hospital: 0.4, school: 0.5, airport: 20, mall: 2.0, railwayStation: 0.8, metroStation: 1.0 }
  },
  {
    id: 5,
    city: "Mumbai",
    area: "Thane",
    address: "505 City Park, Thane West, Mumbai 400601",
    propertyType: "flat",
    size: "1BHK",
    price: 12000,
    amenities: ["parking", "water storage", "power backup"],
    photos: [],
    rating: 3.5,
    reviews: 4,
    owner: "Vikram Singh",
    contact: "+91-9876543214",
    nearbyPlaces: { hospital: 1.2, school: 1.0, airport: 25, mall: 1.8, railwayStation: 2.5, metroStation: 1.5 }
  },
  {
    id: 6,
    city: "Mumbai",
    area: "Fort",
    address: "606 Grand Plaza, Fort, Mumbai 400001",
    propertyType: "flat",
    size: "3BHK",
    price: 40000,
    amenities: ["swimming pool", "gym", "lift", "parking", "security", "library"],
    photos: [],
    rating: 4.8,
    reviews: 30,
    owner: "Ravi Kumar",
    contact: "+91-9876543215",
    nearbyPlaces: { hospital: 0.3, school: 0.4, airport: 22, mall: 0.5, railwayStation: 0.6, metroStation: 0.7 }
  },
  {
    id: 7,
    city: "Mumbai",
    area: "Juhu",
    address: "707 Ocean View, Juhu Tara Road, Mumbai 400049",
    propertyType: "flat",
    size: "2BHK",
    price: 28000,
    amenities: ["swimming pool", "lift", "parking", "gym"],
    photos: [],
    rating: 4.3,
    reviews: 14,
    owner: "Deepak Verma",
    contact: "+91-9876543216",
    nearbyPlaces: { hospital: 0.8, school: 0.7, airport: 8, mall: 1.3, railwayStation: 2.5, metroStation: 1.8 }
  },
  {
    id: 8,
    city: "Mumbai",
    area: "Borivali",
    address: "808 Serenity Park, Borivali West, Mumbai 400092",
    propertyType: "flat",
    size: "1BHK",
    price: 14000,
    amenities: ["lift", "parking"],
    photos: [],
    rating: 3.9,
    reviews: 7,
    owner: "Sandhya Gupta",
    contact: "+91-9876543217",
    nearbyPlaces: { hospital: 1.5, school: 1.2, airport: 30, mall: 2.0, railwayStation: 1.8, metroStation: 0.9 }
  },
  {
    id: 9,
    city: "Mumbai",
    area: "Colaba",
    address: "909 Sea Palace, Colaba, Mumbai 400005",
    propertyType: "flat",
    size: "3BHK",
    price: 45000,
    amenities: ["swimming pool", "gym", "lift", "parking", "security", "concierge"],
    photos: [],
    rating: 4.9,
    reviews: 35,
    owner: "Anil Desai",
    contact: "+91-9876543218",
    nearbyPlaces: { hospital: 0.2, school: 0.3, airport: 25, mall: 0.3, railwayStation: 1.0, metroStation: 1.2 }
  },
  {
    id: 10,
    city: "Mumbai",
    area: "Worli",
    address: "1010 Metro Heights, Worli, Mumbai 400018",
    propertyType: "flat",
    size: "2BHK",
    price: 26000,
    amenities: ["swimming pool", "lift", "parking", "security"],
    photos: [],
    rating: 4.4,
    reviews: 16,
    owner: "Pooja Singh",
    contact: "+91-9876543219",
    nearbyPlaces: { hospital: 0.6, school: 0.9, airport: 18, mall: 1.1, railwayStation: 1.5, metroStation: 0.8 }
  },
  {
    id: 11,
    city: "Mumbai",
    area: "Malad",
    address: "1111 Malad Plaza, Malad West, Mumbai 400064",
    propertyType: "flat",
    size: "1BHK",
    price: 13000,
    amenities: ["parking", "water storage"],
    photos: [],
    rating: 3.7,
    reviews: 5,
    owner: "Suresh Nair",
    contact: "+91-9876543220",
    nearbyPlaces: { hospital: 1.8, school: 1.5, airport: 28, mall: 2.2, railwayStation: 2.0, metroStation: 1.1 }
  },
  {
    id: 12,
    city: "Mumbai",
    area: "Vile Parle",
    address: "1212 Airport Court, Vile Parle, Mumbai 400056",
    propertyType: "flat",
    size: "3BHK",
    price: 38000,
    amenities: ["swimming pool", "gym", "lift", "parking"],
    photos: [],
    rating: 4.6,
    reviews: 20,
    owner: "Harsha Reddy",
    contact: "+91-9876543221",
    nearbyPlaces: { hospital: 0.9, school: 1.1, airport: 5, mall: 1.4, railwayStation: 2.8, metroStation: 1.5 }
  },
  {
    id: 13,
    city: "Mumbai",
    area: "Navi Mumbai",
    address: "1313 Pinnacle Towers, Kharghar, Navi Mumbai 410210",
    propertyType: "flat",
    size: "2BHK",
    price: 18000,
    amenities: ["lift", "parking", "gym"],
    photos: [],
    rating: 4.1,
    reviews: 9,
    owner: "Mohit Kapoor",
    contact: "+91-9876543222",
    nearbyPlaces: { hospital: 1.3, school: 1.0, airport: 35, mall: 1.7, railwayStation: 3.0, metroStation: 2.0 }
  },
  {
    id: 14,
    city: "Mumbai",
    area: "Dombivli",
    address: "1414 Crown Residency, Dombivli East, Mumbai 421201",
    propertyType: "flat",
    size: "1BHK",
    price: 11000,
    amenities: ["parking", "power backup"],
    photos: [],
    rating: 3.6,
    reviews: 3,
    owner: "Priya Sharma",
    contact: "+91-9876543223",
    nearbyPlaces: { hospital: 2.0, school: 1.8, airport: 40, mall: 2.5, railwayStation: 2.2, metroStation: 1.8 }
  },
  {
    id: 15,
    city: "Mumbai",
    area: "Kurla",
    address: "1515 Westend Heights, Kurla, Mumbai 400070",
    propertyType: "flat",
    size: "3BHK",
    price: 36000,
    amenities: ["swimming pool", "lift", "parking", "gym"],
    photos: [],
    rating: 4.5,
    reviews: 18,
    owner: "Rohan Gupta",
    contact: "+91-9876543224",
    nearbyPlaces: { hospital: 0.7, school: 0.8, airport: 16, mall: 1.0, railwayStation: 1.8, metroStation: 0.6 }
  },
  {
    id: 16,
    city: "Mumbai",
    area: "Kala Ghoda",
    address: "1616 Heritage Mansion, Kala Ghoda, Mumbai 400004",
    propertyType: "flat",
    size: "2BHK",
    price: 27000,
    amenities: ["lift", "parking", "security"],
    photos: [],
    rating: 4.2,
    reviews: 11,
    owner: "Sakshi Patel",
    contact: "+91-9876543225",
    nearbyPlaces: { hospital: 0.5, school: 0.6, airport: 21, mall: 0.8, railwayStation: 0.7, metroStation: 0.9 }
  },
  {
    id: 17,
    city: "Mumbai",
    area: "Mahim",
    address: "1717 Beachfront Plaza, Mahim, Mumbai 400016",
    propertyType: "flat",
    size: "1BHK",
    price: 16000,
    amenities: ["lift", "parking"],
    photos: [],
    rating: 3.8,
    reviews: 6,
    owner: "Arjun Singh",
    contact: "+91-9876543226",
    nearbyPlaces: { hospital: 0.9, school: 0.7, airport: 14, mall: 1.6, railwayStation: 1.2, metroStation: 0.4 }
  },
  {
    id: 18,
    city: "Mumbai",
    area: "Chembur",
    address: "1818 Central Heights, Chembur, Mumbai 400074",
    propertyType: "flat",
    size: "3BHK",
    price: 34000,
    amenities: ["swimming pool", "gym", "lift", "parking"],
    photos: [],
    rating: 4.4,
    reviews: 15,
    owner: "Anjali Mishra",
    contact: "+91-9876543227",
    nearbyPlaces: { hospital: 1.1, school: 1.3, airport: 19, mall: 1.5, railwayStation: 2.3, metroStation: 1.0 }
  },
  {
    id: 19,
    city: "Mumbai",
    area: "Byculla",
    address: "1919 South Heights, Byculla, Mumbai 400008",
    propertyType: "flat",
    size: "2BHK",
    price: 23000,
    amenities: ["lift", "parking", "water storage"],
    photos: [],
    rating: 3.9,
    reviews: 7,
    owner: "Vikram Patel",
    contact: "+91-9876543228",
    nearbyPlaces: { hospital: 0.4, school: 0.5, airport: 23, mall: 1.9, railwayStation: 0.5, metroStation: 1.1 }
  },
  {
    id: 20,
    city: "Mumbai",
    area: "Parel",
    address: "2020 Industrial Plaza, Parel, Mumbai 400012",
    propertyType: "flat",
    size: "1BHK",
    price: 15500,
    amenities: ["parking", "security"],
    photos: [],
    rating: 3.7,
    reviews: 4,
    owner: "Swati Verma",
    contact: "+91-9876543229",
    nearbyPlaces: { hospital: 0.8, school: 1.0, airport: 17, mall: 1.3, railwayStation: 0.9, metroStation: 0.7 }
  },
  {
    id: 21,
    city: "Mumbai",
    area: "Kandivali",
    address: "2121 North Star, Kandivali West, Mumbai 400067",
    propertyType: "flat",
    size: "3BHK",
    price: 32000,
    amenities: ["gym", "lift", "parking"],
    photos: [],
    rating: 4.3,
    reviews: 13,
    owner: "Nikhil Sharma",
    contact: "+91-9876543230",
    nearbyPlaces: { hospital: 1.4, school: 1.2, airport: 32, mall: 2.1, railwayStation: 2.2, metroStation: 1.3 }
  },
  {
    id: 22,
    city: "Mumbai",
    area: "Santacruz",
    address: "2222 Express Avenue, Santacruz, Mumbai 400054",
    propertyType: "flat",
    size: "2BHK",
    price: 24500,
    amenities: ["swimming pool", "lift", "parking"],
    photos: [],
    rating: 4.2,
    reviews: 10,
    owner: "Divya Reddy",
    contact: "+91-9876543231",
    nearbyPlaces: { hospital: 0.6, school: 0.8, airport: 9, mall: 1.2, railwayStation: 2.3, metroStation: 1.6 }
  },
  {
    id: 23,
    city: "Mumbai",
    area: "Bhandup",
    address: "2323 Central Plaza, Bhandup, Mumbai 400078",
    propertyType: "flat",
    size: "1BHK",
    price: 13500,
    amenities: ["lift", "parking", "power backup"],
    photos: [],
    rating: 3.8,
    reviews: 5,
    owner: "Ashok Kumar",
    contact: "+91-9876543232",
    nearbyPlaces: { hospital: 1.6, school: 1.4, airport: 27, mall: 1.9, railwayStation: 1.9, metroStation: 1.2 }
  },
  {
    id: 24,
    city: "Mumbai",
    area: "Dharavi",
    address: "2424 City Park, Dharavi, Mumbai 400017",
    propertyType: "flat",
    size: "3BHK",
    price: 30000,
    amenities: ["lift", "parking", "gym"],
    photos: [],
    rating: 4.0,
    reviews: 8,
    owner: "Ramesh Kumar",
    contact: "+91-9876543233",
    nearbyPlaces: { hospital: 0.9, school: 0.7, airport: 14, mall: 1.4, railwayStation: 1.1, metroStation: 0.5 }
  },
  {
    id: 25,
    city: "Mumbai",
    area: "Wadala",
    address: "2525 Pride Heights, Wadala, Mumbai 400031",
    propertyType: "flat",
    size: "2BHK",
    price: 21000,
    amenities: ["lift", "parking", "security"],
    photos: [],
    rating: 3.9,
    reviews: 6,
    owner: "Kavya Singh",
    contact: "+91-9876543234",
    nearbyPlaces: { hospital: 0.7, school: 0.6, airport: 19, mall: 1.2, railwayStation: 1.0, metroStation: 0.8 }
  },

  // Bangalore - Villa (20 properties)
  {
    id: 26,
    city: "Bangalore",
    area: "Koramangala",
    address: "2626 Tech Gardens, Koramangala 6th Block, Bangalore 560095",
    propertyType: "villa",
    size: "3BHK",
    price: 45000,
    amenities: ["swimming pool", "gym", "parking", "security"],
    photos: [],
    rating: 4.6,
    reviews: 22,
    owner: "Rajesh Verma",
    contact: "+91-8765432100",
    nearbyPlaces: { hospital: 0.5, school: 0.7, airport: 18, mall: 1.1, railwayStation: 2.5, metroStation: 1.2 }
  },
  {
    id: 27,
    city: "Bangalore",
    area: "Indiranagar",
    address: "2727 Infinity Homes, 12th Main Road, Indiranagar, Bangalore 560038",
    propertyType: "villa",
    size: "4BHK",
    price: 55000,
    amenities: ["swimming pool", "gym", "lift", "parking", "security", "garden"],
    photos: [],
    rating: 4.8,
    reviews: 28,
    owner: "Priya Desai",
    contact: "+91-8765432101",
    nearbyPlaces: { hospital: 0.6, school: 0.8, airport: 20, mall: 1.3, railwayStation: 2.8, metroStation: 1.5 }
  },
  {
    id: 28,
    city: "Bangalore",
    area: "Whitefield",
    address: "2828 Tech Valley, Whitefield Road, Bangalore 560066",
    propertyType: "villa",
    size: "3BHK",
    price: 42000,
    amenities: ["swimming pool", "gym", "parking"],
    photos: [],
    rating: 4.4,
    reviews: 17,
    owner: "Sudhir Sharma",
    contact: "+91-8765432102",
    nearbyPlaces: { hospital: 1.2, school: 1.0, airport: 25, mall: 1.8, railwayStation: 3.2, metroStation: 2.0 }
  },
  {
    id: 29,
    city: "Bangalore",
    area: "Yeshwantpur",
    address: "2929 Green Villas, Yeshwantpur Main Road, Bangalore 560022",
    propertyType: "villa",
    size: "2BHK",
    price: 32000,
    amenities: ["parking", "garden", "security"],
    photos: [],
    rating: 4.1,
    reviews: 9,
    owner: "Ankita Patel",
    contact: "+91-8765432103",
    nearbyPlaces: { hospital: 0.8, school: 0.9, airport: 22, mall: 1.5, railwayStation: 1.8, metroStation: 1.1 }
  },
  {
    id: 30,
    city: "Bangalore",
    area: "Bannerghatta",
    address: "3030 Luxury Estate, Bannerghatta Main Road, Bangalore 560076",
    propertyType: "villa",
    size: "4BHK",
    price: 52000,
    amenities: ["swimming pool", "gym", "parking", "security", "garden"],
    photos: [],
    rating: 4.7,
    reviews: 25,
    owner: "Vikram Singh",
    contact: "+91-8765432104",
    nearbyPlaces: { hospital: 1.5, school: 1.2, airport: 28, mall: 2.0, railwayStation: 3.5, metroStation: 2.2 }
  },
  {
    id: 31,
    city: "Bangalore",
    area: "Sarjapur",
    address: "3131 Premium Paradise, Sarjapur Road, Bangalore 562125",
    propertyType: "villa",
    size: "3BHK",
    price: 40000,
    amenities: ["swimming pool", "parking", "garden"],
    photos: [],
    rating: 4.3,
    reviews: 14,
    owner: "Neha Reddy",
    contact: "+91-8765432105",
    nearbyPlaces: { hospital: 1.8, school: 1.5, airport: 30, mall: 2.3, railwayStation: 3.8, metroStation: 2.5 }
  },
  {
    id: 32,
    city: "Bangalore",
    area: "HSR Layout",
    address: "3232 Lakeside Residences, HSR Layout, Bangalore 560102",
    propertyType: "villa",
    size: "2BHK",
    price: 35000,
    amenities: ["gym", "parking", "security"],
    photos: [],
    rating: 4.2,
    reviews: 11,
    owner: "Rohan Kumar",
    contact: "+91-8765432106",
    nearbyPlaces: { hospital: 0.7, school: 0.6, airport: 19, mall: 1.2, railwayStation: 2.3, metroStation: 1.4 }
  },
  {
    id: 33,
    city: "Bangalore",
    area: "JP Nagar",
    address: "3333 Prestige Towers, JP Nagar 1st Phase, Bangalore 560078",
    propertyType: "villa",
    size: "3BHK",
    price: 44000,
    amenities: ["swimming pool", "gym", "parking", "garden"],
    photos: [],
    rating: 4.5,
    reviews: 19,
    owner: "Sakshi Sharma",
    contact: "+91-8765432107",
    nearbyPlaces: { hospital: 0.9, school: 1.0, airport: 21, mall: 1.4, railwayStation: 2.6, metroStation: 1.6 }
  },
  {
    id: 34,
    city: "Bangalore",
    area: "Domlur",
    address: "3434 Royal Mansion, Domlur, Bangalore 560071",
    propertyType: "villa",
    size: "4BHK",
    price: 58000,
    amenities: ["swimming pool", "gym", "lift", "parking", "security", "garden", "library"],
    photos: [],
    rating: 4.9,
    reviews: 32,
    owner: "Arjun Verma",
    contact: "+91-8765432108",
    nearbyPlaces: { hospital: 0.4, school: 0.5, airport: 17, mall: 0.9, railwayStation: 2.1, metroStation: 1.0 }
  },
  {
    id: 35,
    city: "Bangalore",
    area: "Mahadevapura",
    address: "3535 Tech Estates, Mahadevapura, Bangalore 560048",
    propertyType: "villa",
    size: "3BHK",
    price: 41000,
    amenities: ["swimming pool", "parking", "security"],
    photos: [],
    rating: 4.2,
    reviews: 10,
    owner: "Anjali Gupta",
    contact: "+91-8765432109",
    nearbyPlaces: { hospital: 1.3, school: 1.1, airport: 24, mall: 1.7, railwayStation: 2.9, metroStation: 1.8 }
  },
  {
    id: 36,
    city: "Bangalore",
    area: "Hebbal",
    address: "3636 Greenland Villas, Hebbal, Bangalore 560024",
    propertyType: "villa",
    size: "2BHK",
    price: 33000,
    amenities: ["gym", "parking", "garden"],
    photos: [],
    rating: 4.0,
    reviews: 8,
    owner: "Pooja Verma",
    contact: "+91-8765432110",
    nearbyPlaces: { hospital: 1.1, school: 1.2, airport: 23, mall: 1.6, railwayStation: 2.4, metroStation: 1.3 }
  },
  {
    id: 37,
    city: "Bangalore",
    area: "Ejipura",
    address: "3737 Comfort Heights, Ejipura, Bangalore 560047",
    propertyType: "villa",
    size: "3BHK",
    price: 43000,
    amenities: ["swimming pool", "gym", "parking"],
    photos: [],
    rating: 4.4,
    reviews: 16,
    owner: "Ravi Singh",
    contact: "+91-8765432111",
    nearbyPlaces: { hospital: 0.8, school: 0.9, airport: 20, mall: 1.3, railwayStation: 2.7, metroStation: 1.5 }
  },
  {
    id: 38,
    city: "Bangalore",
    area: "Residency Road",
    address: "3838 Elite Heights, Residency Road, Bangalore 560025",
    propertyType: "villa",
    size: "4BHK",
    price: 56000,
    amenities: ["swimming pool", "gym", "lift", "parking", "security"],
    photos: [],
    rating: 4.7,
    reviews: 26,
    owner: "Divya Singh",
    contact: "+91-8765432112",
    nearbyPlaces: { hospital: 0.5, school: 0.4, airport: 19, mall: 0.8, railwayStation: 2.2, metroStation: 1.2 }
  },
  {
    id: 39,
    city: "Bangalore",
    area: "Ulsoor",
    address: "3939 Central Park, Ulsoor, Bangalore 560008",
    propertyType: "villa",
    size: "2BHK",
    price: 34000,
    amenities: ["parking", "security", "garden"],
    photos: [],
    rating: 4.1,
    reviews: 9,
    owner: "Harsh Patel",
    contact: "+91-8765432113",
    nearbyPlaces: { hospital: 0.6, school: 0.7, airport: 18, mall: 1.0, railwayStation: 2.0, metroStation: 0.9 }
  },
  {
    id: 40,
    city: "Bangalore",
    area: "Banaswadi",
    address: "4040 Modern Residency, Banaswadi Main Road, Bangalore 560033",
    propertyType: "villa",
    size: "3BHK",
    price: 39000,
    amenities: ["gym", "parking", "garden"],
    photos: [],
    rating: 4.2,
    reviews: 12,
    owner: "Swati Gupta",
    contact: "+91-8765432114",
    nearbyPlaces: { hospital: 1.2, school: 1.3, airport: 26, mall: 1.9, railwayStation: 3.1, metroStation: 1.9 }
  },
  {
    id: 41,
    city: "Bangalore",
    area: "Marathahalli",
    address: "4141 Tech Boulevard, Marathahalli, Bangalore 560037",
    propertyType: "villa",
    size: "4BHK",
    price: 51000,
    amenities: ["swimming pool", "gym", "parking", "security"],
    photos: [],
    rating: 4.6,
    reviews: 23,
    owner: "Nikhil Sharma",
    contact: "+91-8765432115",
    nearbyPlaces: { hospital: 1.4, school: 1.5, airport: 27, mall: 2.1, railwayStation: 3.3, metroStation: 2.1 }
  },
  {
    id: 42,
    city: "Bangalore",
    area: "Chikkalasandra",
    address: "4242 Country Estate, Chikkalasandra, Bangalore 560063",
    propertyType: "villa",
    size: "3BHK",
    price: 38000,
    amenities: ["parking", "garden", "security"],
    photos: [],
    rating: 3.9,
    reviews: 7,
    owner: "Kavya Sharma",
    contact: "+91-8765432116",
    nearbyPlaces: { hospital: 1.6, school: 1.4, airport: 29, mall: 2.2, railwayStation: 3.4, metroStation: 2.2 }
  },
  {
    id: 43,
    city: "Bangalore",
    area: "Murgeshpalya",
    address: "4343 Sunrise Gardens, Murgeshpalya, Bangalore 560017",
    propertyType: "villa",
    size: "2BHK",
    price: 31000,
    amenities: ["gym", "parking"],
    photos: [],
    rating: 4.0,
    reviews: 8,
    owner: "Mohan Reddy",
    contact: "+91-8765432117",
    nearbyPlaces: { hospital: 1.0, school: 1.1, airport: 22, mall: 1.5, railwayStation: 2.5, metroStation: 1.4 }
  },
  {
    id: 44,
    city: "Bangalore",
    area: "Jayamahal",
    address: "4444 Dream Villas, Jayamahal, Bangalore 560082",
    propertyType: "villa",
    size: "3BHK",
    price: 42000,
    amenities: ["swimming pool", "parking", "garden"],
    photos: [],
    rating: 4.3,
    reviews: 15,
    owner: "Shreya Singh",
    contact: "+91-8765432118",
    nearbyPlaces: { hospital: 0.9, school: 1.0, airport: 21, mall: 1.3, railwayStation: 2.4, metroStation: 1.3 }
  },
  {
    id: 45,
    city: "Bangalore",
    area: "Sumadhura",
    address: "4545 Suburban Paradise, Sumadhura, Bangalore 560100",
    propertyType: "villa",
    size: "4BHK",
    price: 54000,
    amenities: ["swimming pool", "gym", "lift", "parking", "security", "garden"],
    photos: [],
    rating: 4.8,
    reviews: 29,
    owner: "Deepak Verma",
    contact: "+91-8765432119",
    nearbyPlaces: { hospital: 1.3, school: 1.2, airport: 26, mall: 1.8, railwayStation: 3.0, metroStation: 1.9 }
  },

  // Delhi - Bungalow (20 properties)
  {
    id: 46,
    city: "Delhi",
    area: "South Delhi",
    address: "4646 Royal Estate, Deer Park, South Delhi 110003",
    propertyType: "bungalow",
    size: "4BHK",
    price: 60000,
    amenities: ["swimming pool", "gym", "parking", "security", "garden"],
    photos: [],
    rating: 4.7,
    reviews: 27,
    owner: "Manoj Kumar",
    contact: "+91-7654321000",
    nearbyPlaces: { hospital: 0.4, school: 0.5, airport: 20, mall: 1.0, railwayStation: 2.2, metroStation: 0.8 }
  },
  {
    id: 47,
    city: "Delhi",
    area: "New Delhi",
    address: "4747 Parliament Heights, New Delhi 110001",
    propertyType: "bungalow",
    size: "3BHK",
    price: 48000,
    amenities: ["gym", "parking", "security"],
    photos: [],
    rating: 4.4,
    reviews: 18,
    owner: "Rajesh Singh",
    contact: "+91-7654321001",
    nearbyPlaces: { hospital: 0.5, school: 0.6, airport: 18, mall: 0.9, railwayStation: 1.8, metroStation: 0.7 }
  },
  {
    id: 48,
    city: "Delhi",
    area: "Greater Noida",
    address: "4848 Galaxy Residences, Greater Noida 201308",
    propertyType: "bungalow",
    size: "4BHK",
    price: 58000,
    amenities: ["swimming pool", "gym", "parking", "garden"],
    photos: [],
    rating: 4.5,
    reviews: 21,
    owner: "Priya Sharma",
    contact: "+91-7654321002",
    nearbyPlaces: { hospital: 1.1, school: 1.2, airport: 30, mall: 1.8, railwayStation: 2.8, metroStation: 1.5 }
  },
  {
    id: 49,
    city: "Delhi",
    area: "Gurugram",
    address: "4949 Corporate Towers, MG Road, Gurugram 122001",
    propertyType: "bungalow",
    size: "3BHK",
    price: 50000,
    amenities: ["swimming pool", "gym", "lift", "parking", "security"],
    photos: [],
    rating: 4.6,
    reviews: 24,
    owner: "Vikram Patel",
    contact: "+91-7654321003",
    nearbyPlaces: { hospital: 0.7, school: 0.8, airport: 22, mall: 1.2, railwayStation: 2.5, metroStation: 1.3 }
  },
  {
    id: 50,
    city: "Delhi",
    area: "Dwarka",
    address: "5050 Residential Park, Dwarka, Delhi 110077",
    propertyType: "bungalow",
    size: "2BHK",
    price: 38000,
    amenities: ["parking", "security", "garden"],
    photos: [],
    rating: 4.0,
    reviews: 9,
    owner: "Neha Gupta",
    contact: "+91-7654321004",
    nearbyPlaces: { hospital: 1.2, school: 1.3, airport: 25, mall: 1.6, railwayStation: 2.2, metroStation: 1.0 }
  },
  {
    id: 51,
    city: "Delhi",
    area: "Noida",
    address: "5151 Tech Park, Noida City Center, Noida 201301",
    propertyType: "bungalow",
    size: "3BHK",
    price: 46000,
    amenities: ["gym", "parking", "security"],
    photos: [],
    rating: 4.2,
    reviews: 13,
    owner: "Suresh Verma",
    contact: "+91-7654321005",
    nearbyPlaces: { hospital: 0.8, school: 0.9, airport: 28, mall: 1.5, railwayStation: 2.3, metroStation: 1.2 }
  },
  {
    id: 52,
    city: "Delhi",
    area: "Ghaziabad",
    address: "5252 Pinnacle Plaza, Ghaziabad 201001",
    propertyType: "bungalow",
    size: "4BHK",
    price: 55000,
    amenities: ["swimming pool", "parking", "garden"],
    photos: [],
    rating: 4.3,
    reviews: 16,
    owner: "Anjali Singh",
    contact: "+91-7654321006",
    nearbyPlaces: { hospital: 1.3, school: 1.4, airport: 32, mall: 1.9, railwayStation: 2.6, metroStation: 1.6 }
  },
  {
    id: 53,
    city: "Delhi",
    area: "West Delhi",
    address: "5353 Heritage Villas, West Delhi 110015",
    propertyType: "bungalow",
    size: "3BHK",
    price: 45000,
    amenities: ["gym", "parking", "garden"],
    photos: [],
    rating: 4.1,
    reviews: 10,
    owner: "Ravi Sharma",
    contact: "+91-7654321007",
    nearbyPlaces: { hospital: 0.9, school: 1.0, airport: 23, mall: 1.3, railwayStation: 2.0, metroStation: 1.1 }
  },
  {
    id: 54,
    city: "Delhi",
    area: "Faridabad",
    address: "5454 Industrial Estate, Faridabad 121001",
    propertyType: "bungalow",
    size: "2BHK",
    price: 36000,
    amenities: ["parking", "garden", "security"],
    photos: [],
    rating: 3.9,
    reviews: 7,
    owner: "Pooja Kumar",
    contact: "+91-7654321008",
    nearbyPlaces: { hospital: 1.4, school: 1.5, airport: 35, mall: 2.0, railwayStation: 2.8, metroStation: 1.8 }
  },
  {
    id: 55,
    city: "Delhi",
    area: "East Delhi",
    address: "5555 Pride Residences, East Delhi 110091",
    propertyType: "bungalow",
    size: "4BHK",
    price: 57000,
    amenities: ["swimming pool", "gym", "parking", "security", "garden"],
    photos: [],
    rating: 4.4,
    reviews: 19,
    owner: "Arjun Verma",
    contact: "+91-7654321009",
    nearbyPlaces: { hospital: 0.6, school: 0.7, airport: 21, mall: 1.1, railwayStation: 1.9, metroStation: 0.9 }
  },
  {
    id: 56,
    city: "Delhi",
    area: "North Delhi",
    address: "5656 Green Heights, North Delhi 110006",
    propertyType: "bungalow",
    size: "3BHK",
    price: 43000,
    amenities: ["gym", "parking"],
    photos: [],
    rating: 4.0,
    reviews: 8,
    owner: "Divya Patel",
    contact: "+91-7654321010",
    nearbyPlaces: { hospital: 1.0, school: 1.1, airport: 24, mall: 1.4, railwayStation: 2.1, metroStation: 1.2 }
  },
  {
    id: 57,
    city: "Delhi",
    area: "Gurgaon",
    address: "5757 Cyber City, Gurgaon 122002",
    propertyType: "bungalow",
    size: "4BHK",
    price: 62000,
    amenities: ["swimming pool", "gym", "lift", "parking", "security", "garden", "concierge"],
    photos: [],
    rating: 4.8,
    reviews: 30,
    owner: "Harsha Reddy",
    contact: "+91-7654321011",
    nearbyPlaces: { hospital: 0.5, school: 0.6, airport: 20, mall: 0.8, railwayStation: 2.3, metroStation: 1.2 }
  },
  {
    id: 58,
    city: "Delhi",
    area: "Sector 63",
    address: "5858 Tech Sector, Sector 63, Noida 201301",
    propertyType: "bungalow",
    size: "3BHK",
    price: 47000,
    amenities: ["swimming pool", "gym", "parking"],
    photos: [],
    rating: 4.3,
    reviews: 14,
    owner: "Mohan Singh",
    contact: "+91-7654321012",
    nearbyPlaces: { hospital: 0.8, school: 0.9, airport: 21, mall: 1.2, railwayStation: 2.4, metroStation: 1.3 }
  },
  {
    id: 59,
    city: "Delhi",
    area: "Sector 56",
    address: "5959 Sunrise Sector, Sector 56, Gurgaon 122002",
    propertyType: "bungalow",
    size: "2BHK",
    price: 37000,
    amenities: ["parking", "security"],
    photos: [],
    rating: 3.8,
    reviews: 5,
    owner: "Sakshi Verma",
    contact: "+91-7654321013",
    nearbyPlaces: { hospital: 0.9, school: 1.0, airport: 22, mall: 1.3, railwayStation: 2.2, metroStation: 1.2 }
  },
  {
    id: 60,
    city: "Delhi",
    area: "Sector 48",
    address: "6060 Business District, Sector 48, Gurgaon 122001",
    propertyType: "bungalow",
    size: "3BHK",
    price: 44000,
    amenities: ["gym", "parking", "garden"],
    photos: [],
    rating: 4.1,
    reviews: 11,
    owner: "Kavya Reddy",
    contact: "+91-7654321014",
    nearbyPlaces: { hospital: 1.1, school: 1.2, airport: 23, mall: 1.4, railwayStation: 2.5, metroStation: 1.4 }
  },
  {
    id: 61,
    city: "Delhi",
    area: "Sector 52",
    address: "6161 Modern Plaza, Sector 52, Gurgaon 122003",
    propertyType: "bungalow",
    size: "4BHK",
    price: 59000,
    amenities: ["swimming pool", "gym", "lift", "parking", "security"],
    photos: [],
    rating: 4.5,
    reviews: 22,
    owner: "Shreya Sharma",
    contact: "+91-7654321015",
    nearbyPlaces: { hospital: 0.7, school: 0.8, airport: 21, mall: 1.1, railwayStation: 2.3, metroStation: 1.2 }
  },
  {
    id: 62,
    city: "Delhi",
    area: "Sector 37",
    address: "6262 Central Heights, Sector 37, Gurgaon 122001",
    propertyType: "bungalow",
    size: "2BHK",
    price: 35000,
    amenities: ["parking", "garden"],
    photos: [],
    rating: 3.7,
    reviews: 4,
    owner: "Nikhil Patel",
    contact: "+91-7654321016",
    nearbyPlaces: { hospital: 1.2, school: 1.3, airport: 24, mall: 1.5, railwayStation: 2.6, metroStation: 1.5 }
  },
  {
    id: 63,
    city: "Delhi",
    area: "Sector 31",
    address: "6363 Premium Residences, Sector 31, Gurgaon 122002",
    propertyType: "bungalow",
    size: "3BHK",
    price: 42000,
    amenities: ["swimming pool", "parking", "security"],
    photos: [],
    rating: 4.2,
    reviews: 12,
    owner: "Priya Verma",
    contact: "+91-7654321017",
    nearbyPlaces: { hospital: 0.9, school: 1.0, airport: 22, mall: 1.2, railwayStation: 2.2, metroStation: 1.1 }
  },
  {
    id: 64,
    city: "Delhi",
    area: "Sector 18",
    address: "6464 Leisure Avenue, Sector 18, Gurgaon 122001",
    propertyType: "bungalow",
    size: "4BHK",
    price: 56000,
    amenities: ["swimming pool", "gym", "parking", "garden"],
    photos: [],
    rating: 4.4,
    reviews: 20,
    owner: "Ashok Sharma",
    contact: "+91-7654321018",
    nearbyPlaces: { hospital: 0.8, school: 0.9, airport: 23, mall: 1.3, railwayStation: 2.4, metroStation: 1.2 }
  },
  {
    id: 65,
    city: "Delhi",
    area: "Sector 9",
    address: "6565 Green Valley, Sector 9, Gurgaon 122001",
    propertyType: "bungalow",
    size: "3BHK",
    price: 41000,
    amenities: ["gym", "parking"],
    photos: [],
    rating: 3.9,
    reviews: 6,
    owner: "Deepak Singh",
    contact: "+91-7654321019",
    nearbyPlaces: { hospital: 1.0, school: 1.1, airport: 24, mall: 1.4, railwayStation: 2.5, metroStation: 1.3 }
  },

  // Hyderabad - Penthouse (15 properties)
  {
    id: 66,
    city: "Hyderabad",
    area: "Banjara Hills",
    address: "6666 Sky View Tower, Banjara Hills, Hyderabad 500034",
    propertyType: "penthouse",
    size: "3BHK",
    price: 50000,
    amenities: ["swimming pool", "gym", "lift", "parking", "security", "concierge"],
    photos: [],
    rating: 4.7,
    reviews: 24,
    owner: "Ravi Kumar",
    contact: "+91-6543210000",
    nearbyPlaces: { hospital: 0.4, school: 0.5, airport: 16, mall: 0.8, railwayStation: 2.0, metroStation: 0.9 }
  },
  {
    id: 67,
    city: "Hyderabad",
    area: "Jubilee Hills",
    address: "6767 Jubilee Towers, Jubilee Hills Road No. 36, Hyderabad 500033",
    propertyType: "penthouse",
    size: "4BHK",
    price: 65000,
    amenities: ["swimming pool", "gym", "lift", "parking", "security", "concierge", "library"],
    photos: [],
    rating: 4.9,
    reviews: 33,
    owner: "Sakshi Gupta",
    contact: "+91-6543210001",
    nearbyPlaces: { hospital: 0.5, school: 0.6, airport: 17, mall: 0.9, railwayStation: 2.1, metroStation: 1.0 }
  },
  {
    id: 68,
    city: "Hyderabad",
    area: "Madhapur",
    address: "6868 Tech Plaza, Madhapur, Hyderabad 500081",
    propertyType: "penthouse",
    size: "3BHK",
    price: 48000,
    amenities: ["swimming pool", "gym", "lift", "parking", "security"],
    photos: [],
    rating: 4.5,
    reviews: 19,
    owner: "Arjun Singh",
    contact: "+91-6543210002",
    nearbyPlaces: { hospital: 0.6, school: 0.7, airport: 18, mall: 1.0, railwayStation: 2.2, metroStation: 1.1 }
  },
  {
    id: 69,
    city: "Hyderabad",
    area: "Hitec City",
    address: "6969 Cyber Tower, HITEC City, Hyderabad 500081",
    propertyType: "penthouse",
    size: "4BHK",
    price: 62000,
    amenities: ["swimming pool", "gym", "lift", "parking", "security", "concierge"],
    photos: [],
    rating: 4.8,
    reviews: 31,
    owner: "Divya Sharma",
    contact: "+91-6543210003",
    nearbyPlaces: { hospital: 0.7, school: 0.8, airport: 19, mall: 1.1, railwayStation: 2.3, metroStation: 1.2 }
  },
  {
    id: 70,
    city: "Hyderabad",
    area: "Kondapur",
    address: "7070 Kondapur Heights, Kondapur, Hyderabad 500084",
    propertyType: "penthouse",
    size: "3BHK",
    price: 45000,
    amenities: ["gym", "lift", "parking", "security"],
    photos: [],
    rating: 4.2,
    reviews: 12,
    owner: "Pooja Patel",
    contact: "+91-6543210004",
    nearbyPlaces: { hospital: 0.8, school: 0.9, airport: 20, mall: 1.2, railwayStation: 2.4, metroStation: 1.3 }
  },
  {
    id: 71,
    city: "Hyderabad",
    area: "Gachibowli",
    address: "7171 Gachibowli Towers, Gachibowli, Hyderabad 500032",
    propertyType: "penthouse",
    size: "4BHK",
    price: 63000,
    amenities: ["swimming pool", "gym", "lift", "parking", "security", "concierge"],
    photos: [],
    rating: 4.6,
    reviews: 22,
    owner: "Nikhil Verma",
    contact: "+91-6543210005",
    nearbyPlaces: { hospital: 0.9, school: 1.0, airport: 21, mall: 1.3, railwayStation: 2.5, metroStation: 1.4 }
  },
  {
    id: 72,
    city: "Hyderabad",
    area: "Kukatpalli",
    address: "7272 Kukatpalli Plaza, Kukatpalli, Hyderabad 500072",
    propertyType: "penthouse",
    size: "3BHK",
    price: 42000,
    amenities: ["gym", "lift", "parking"],
    photos: [],
    rating: 4.0,
    reviews: 8,
    owner: "Kavya Singh",
    contact: "+91-6543210006",
    nearbyPlaces: { hospital: 1.0, school: 1.1, airport: 22, mall: 1.4, railwayStation: 2.6, metroStation: 1.5 }
  },
  {
    id: 73,
    city: "Hyderabad",
    area: "Filmnagar",
    address: "7373 Filmnagar Heights, Filmnagar, Hyderabad 500033",
    propertyType: "penthouse",
    size: "4BHK",
    price: 60000,
    amenities: ["swimming pool", "gym", "lift", "parking", "security"],
    photos: [],
    rating: 4.4,
    reviews: 16,
    owner: "Shreya Reddy",
    contact: "+91-6543210007",
    nearbyPlaces: { hospital: 0.7, school: 0.8, airport: 18, mall: 1.0, railwayStation: 2.1, metroStation: 1.0 }
  },
  {
    id: 74,
    city: "Hyderabad",
    area: "Secunderabad",
    address: "7474 Secunderabad Heights, Secunderabad, Hyderabad 500003",
    propertyType: "penthouse",
    size: "3BHK",
    price: 43000,
    amenities: ["lift", "parking", "security"],
    photos: [],
    rating: 4.1,
    reviews: 9,
    owner: "Mohan Verma",
    contact: "+91-6543210008",
    nearbyPlaces: { hospital: 0.5, school: 0.6, airport: 17, mall: 0.9, railwayStation: 1.9, metroStation: 0.8 }
  },
  {
    id: 75,
    city: "Hyderabad",
    area: "Rajendranagar",
    address: "7575 Rajendra Heights, Rajendranagar, Hyderabad 500061",
    propertyType: "penthouse",
    size: "4BHK",
    price: 61000,
    amenities: ["swimming pool", "gym", "lift", "parking", "security", "concierge"],
    photos: [],
    rating: 4.5,
    reviews: 20,
    owner: "Anjali Verma",
    contact: "+91-6543210009",
    nearbyPlaces: { hospital: 1.1, school: 1.2, airport: 23, mall: 1.5, railwayStation: 2.7, metroStation: 1.6 }
  },
  {
    id: 76,
    city: "Hyderabad",
    area: "Mehdipatnam",
    address: "7676 Mehdi Heights, Mehdipatnam, Hyderabad 500028",
    propertyType: "penthouse",
    size: "3BHK",
    price: 44000,
    amenities: ["gym", "lift", "parking", "security"],
    photos: [],
    rating: 4.2,
    reviews: 11,
    owner: "Ashok Patel",
    contact: "+91-6543210010",
    nearbyPlaces: { hospital: 0.8, school: 0.9, airport: 19, mall: 1.1, railwayStation: 2.2, metroStation: 1.1 }
  },
  {
    id: 77,
    city: "Hyderabad",
    area: "Charminar",
    address: "7777 Old City Tower, Charminar, Hyderabad 500002",
    propertyType: "penthouse",
    size: "2BHK",
    price: 35000,
    amenities: ["lift", "parking"],
    photos: [],
    rating: 3.8,
    reviews: 5,
    owner: "Priya Kumar",
    contact: "+91-6543210011",
    nearbyPlaces: { hospital: 0.3, school: 0.4, airport: 20, mall: 0.7, railwayStation: 1.5, metroStation: 0.6 }
  },
  {
    id: 78,
    city: "Hyderabad",
    area: "Abids",
    address: "7878 Abids Plaza, Abids, Hyderabad 500001",
    propertyType: "penthouse",
    size: "3BHK",
    price: 46000,
    amenities: ["gym", "lift", "parking", "security"],
    photos: [],
    rating: 4.3,
    reviews: 14,
    owner: "Ravi Reddy",
    contact: "+91-6543210012",
    nearbyPlaces: { hospital: 0.4, school: 0.5, airport: 19, mall: 0.8, railwayStation: 1.6, metroStation: 0.7 }
  },
  {
    id: 79,
    city: "Hyderabad",
    area: "Nampally",
    address: "7979 Nampally Tower, Nampally, Hyderabad 500001",
    propertyType: "penthouse",
    size: "4BHK",
    price: 64000,
    amenities: ["swimming pool", "gym", "lift", "parking", "security", "concierge"],
    photos: [],
    rating: 4.7,
    reviews: 26,
    owner: "Deepak Gupta",
    contact: "+91-6543210013",
    nearbyPlaces: { hospital: 0.3, school: 0.4, airport: 21, mall: 0.7, railwayStation: 1.7, metroStation: 0.8 }
  },
  {
    id: 80,
    city: "Hyderabad",
    area: "Mylapore",
    address: "8080 Mylapore Heights, Mylapore, Hyderabad 500020",
    propertyType: "penthouse",
    size: "3BHK",
    price: 41000,
    amenities: ["lift", "parking", "security"],
    photos: [],
    rating: 3.9,
    reviews: 6,
    owner: "Swati Patel",
    contact: "+91-6543210014",
    nearbyPlaces: { hospital: 0.6, school: 0.7, airport: 18, mall: 0.9, railwayStation: 2.0, metroStation: 0.9 }
  },

  // Pune - Mixed Properties (20 properties)
  {
    id: 81,
    city: "Pune",
    area: "Baner",
    address: "8181 Baner Heights, Baner Road, Pune 411045",
    propertyType: "flat",
    size: "2BHK",
    price: 18000,
    amenities: ["gym", "parking", "security"],
    photos: [],
    rating: 4.2,
    reviews: 11,
    owner: "Harsha Kumar",
    contact: "+91-5432100000",
    nearbyPlaces: { hospital: 0.8, school: 0.9, airport: 15, mall: 1.2, railwayStation: 2.2, metroStation: 1.1 }
  },
  {
    id: 82,
    city: "Pune",
    area: "Aundh",
    address: "8282 Aundh Center, Aundh, Pune 411007",
    propertyType: "flat",
    size: "1BHK",
    price: 12000,
    amenities: ["parking", "water storage"],
    photos: [],
    rating: 3.8,
    reviews: 5,
    owner: "Vasantha Singh",
    contact: "+91-5432100001",
    nearbyPlaces: { hospital: 1.0, school: 1.1, airport: 17, mall: 1.4, railwayStation: 2.3, metroStation: 1.2 }
  },
  {
    id: 83,
    city: "Pune",
    area: "Hinjewadi",
    address: "8383 Tech Park, Hinjewadi Phase 1, Pune 411057",
    propertyType: "villa",
    size: "3BHK",
    price: 42000,
    amenities: ["swimming pool", "gym", "parking", "garden"],
    photos: [],
    rating: 4.5,
    reviews: 20,
    owner: "Srinivas Reddy",
    contact: "+91-5432100002",
    nearbyPlaces: { hospital: 1.2, school: 1.3, airport: 20, mall: 1.6, railwayStation: 2.6, metroStation: 1.5 }
  },
  {
    id: 84,
    city: "Pune",
    area: "Kalyani Nagar",
    address: "8484 Kalyani Plaza, Kalyani Nagar, Pune 411006",
    propertyType: "flat",
    size: "3BHK",
    price: 28000,
    amenities: ["swimming pool", "gym", "lift", "parking"],
    photos: [],
    rating: 4.4,
    reviews: 16,
    owner: "Manasa Verma",
    contact: "+91-5432100003",
    nearbyPlaces: { hospital: 0.6, school: 0.7, airport: 14, mall: 1.0, railwayStation: 2.0, metroStation: 0.9 }
  },
  {
    id: 85,
    city: "Pune",
    area: "Viman Nagar",
    address: "8585 Viman Towers, Viman Nagar, Pune 411014",
    propertyType: "villa",
    size: "4BHK",
    price: 52000,
    amenities: ["swimming pool", "gym", "parking", "security", "garden"],
    photos: [],
    rating: 4.6,
    reviews: 23,
    owner: "Atul Kumar",
    contact: "+91-5432100004",
    nearbyPlaces: { hospital: 0.9, school: 1.0, airport: 8, mall: 1.3, railwayStation: 2.4, metroStation: 1.3 }
  },
  {
    id: 86,
    city: "Pune",
    area: "Kothrud",
    address: "8686 Kothrud Heights, Kothrud, Pune 411038",
    propertyType: "flat",
    size: "2BHK",
    price: 19000,
    amenities: ["lift", "parking", "gym"],
    photos: [],
    rating: 4.1,
    reviews: 9,
    owner: "Geeta Patel",
    contact: "+91-5432100005",
    nearbyPlaces: { hospital: 0.7, school: 0.8, airport: 16, mall: 1.1, railwayStation: 2.1, metroStation: 1.0 }
  },
  {
    id: 87,
    city: "Pune",
    area: "Shivaji Nagar",
    address: "8787 Shivaji Plaza, Shivaji Nagar, Pune 411005",
    propertyType: "flat",
    size: "1BHK",
    price: 13000,
    amenities: ["lift", "parking"],
    photos: [],
    rating: 3.9,
    reviews: 6,
    owner: "Jayesh Kumar",
    contact: "+91-5432100006",
    nearbyPlaces: { hospital: 0.5, school: 0.6, airport: 13, mall: 0.9, railwayStation: 1.8, metroStation: 0.8 }
  },
  {
    id: 88,
    city: "Pune",
    area: "Magarpatta",
    address: "8888 Magarpatta Estate, Hadapsar, Pune 411028",
    propertyType: "villa",
    size: "3BHK",
    price: 40000,
    amenities: ["gym", "parking", "garden"],
    photos: [],
    rating: 4.3,
    reviews: 15,
    owner: "Kavya Kumar",
    contact: "+91-5432100007",
    nearbyPlaces: { hospital: 1.1, school: 1.2, airport: 19, mall: 1.5, railwayStation: 2.5, metroStation: 1.4 }
  },
  {
    id: 89,
    city: "Pune",
    area: "Wagholi",
    address: "8989 Wagholi Tower, Wagholi, Pune 412207",
    propertyType: "flat",
    size: "3BHK",
    price: 26000,
    amenities: ["gym", "lift", "parking"],
    photos: [],
    rating: 4.2,
    reviews: 12,
    owner: "Suneel Singh",
    contact: "+91-5432100008",
    nearbyPlaces: { hospital: 1.3, school: 1.4, airport: 21, mall: 1.7, railwayStation: 2.7, metroStation: 1.6 }
  },
  {
    id: 90,
    city: "Pune",
    area: "Chakan",
    address: "9090 Chakan Park, Chakan, Pune 410501",
    propertyType: "villa",
    size: "4BHK",
    price: 50000,
    amenities: ["swimming pool", "parking", "garden"],
    photos: [],
    rating: 4.4,
    reviews: 18,
    owner: "Rekha Verma",
    contact: "+91-5432100009",
    nearbyPlaces: { hospital: 1.5, school: 1.6, airport: 25, mall: 2.0, railwayStation: 3.0, metroStation: 1.9 }
  },
  {
    id: 91,
    city: "Pune",
    area: "Hadapsar",
    address: "9191 Hadapsar Plaza, Hadapsar, Pune 411028",
    propertyType: "flat",
    size: "2BHK",
    price: 17000,
    amenities: ["parking", "gym"],
    photos: [],
    rating: 4.0,
    reviews: 8,
    owner: "Manish Patel",
    contact: "+91-5432100010",
    nearbyPlaces: { hospital: 0.8, school: 0.9, airport: 17, mall: 1.3, railwayStation: 2.3, metroStation: 1.2 }
  },
  {
    id: 92,
    city: "Pune",
    area: "Yerwada",
    address: "9292 Yerwada Heights, Yerwada, Pune 411006",
    propertyType: "flat",
    size: "1BHK",
    price: 11500,
    amenities: ["parking", "water storage"],
    photos: [],
    rating: 3.7,
    reviews: 4,
    owner: "Renu Sharma",
    contact: "+91-5432100011",
    nearbyPlaces: { hospital: 0.6, school: 0.7, airport: 12, mall: 1.0, railwayStation: 1.7, metroStation: 0.7 }
  },
  {
    id: 93,
    city: "Pune",
    area: "Pimple Saudagar",
    address: "9393 Pimple Plaza, Pimple Saudagar, Pune 411027",
    propertyType: "villa",
    size: "3BHK",
    price: 41000,
    amenities: ["swimming pool", "parking", "security"],
    photos: [],
    rating: 4.3,
    reviews: 14,
    owner: "Vishal Kumar",
    contact: "+91-5432100012",
    nearbyPlaces: { hospital: 1.0, school: 1.1, airport: 18, mall: 1.4, railwayStation: 2.4, metroStation: 1.3 }
  },
  {
    id: 94,
    city: "Pune",
    area: "Pimple Gurav",
    address: "9494 Gurav Heights, Pimple Gurav, Pune 411061",
    propertyType: "flat",
    size: "3BHK",
    price: 27000,
    amenities: ["gym", "lift", "parking", "security"],
    photos: [],
    rating: 4.3,
    reviews: 13,
    owner: "Mridula Singh",
    contact: "+91-5432100013",
    nearbyPlaces: { hospital: 0.9, school: 1.0, airport: 19, mall: 1.3, railwayStation: 2.3, metroStation: 1.2 }
  },
  {
    id: 95,
    city: "Pune",
    area: "Koregaon Park",
    address: "9595 Koregaon Estate, Koregaon Park, Pune 411001",
    propertyType: "villa",
    size: "4BHK",
    price: 51000,
    amenities: ["swimming pool", "gym", "parking", "security", "garden"],
    photos: [],
    rating: 4.5,
    reviews: 21,
    owner: "Anita Verma",
    contact: "+91-5432100014",
    nearbyPlaces: { hospital: 0.7, school: 0.8, airport: 15, mall: 1.1, railwayStation: 2.1, metroStation: 1.0 }
  },
  {
    id: 96,
    city: "Pune",
    area: "Sahakari Nagar",
    address: "9696 Sahakari Plaza, Sahakari Nagar, Pune 411009",
    propertyType: "flat",
    size: "2BHK",
    price: 16500,
    amenities: ["lift", "parking"],
    photos: [],
    rating: 3.9,
    reviews: 7,
    owner: "Nitin Sharma",
    contact: "+91-5432100015",
    nearbyPlaces: { hospital: 0.8, school: 0.9, airport: 14, mall: 1.2, railwayStation: 2.0, metroStation: 0.9 }
  },
  {
    id: 97,
    city: "Pune",
    area: "Bawdhan",
    address: "9797 Bawdhan Center, Bawdhan, Pune 411021",
    propertyType: "flat",
    size: "1BHK",
    price: 12500,
    amenities: ["parking", "gym"],
    photos: [],
    rating: 3.8,
    reviews: 5,
    owner: "Shreya Patel",
    contact: "+91-5432100016",
    nearbyPlaces: { hospital: 1.1, school: 1.2, airport: 18, mall: 1.5, railwayStation: 2.5, metroStation: 1.4 }
  },
  {
    id: 98,
    city: "Pune",
    area: "Bhosari",
    address: "9898 Bhosari Heights, Bhosari, Pune 411039",
    propertyType: "villa",
    size: "3BHK",
    price: 39000,
    amenities: ["gym", "parking", "garden"],
    photos: [],
    rating: 4.2,
    reviews: 11,
    owner: "Mohit Verma",
    contact: "+91-5432100017",
    nearbyPlaces: { hospital: 1.3, school: 1.4, airport: 22, mall: 1.8, railwayStation: 2.8, metroStation: 1.7 }
  },
  {
    id: 99,
    city: "Pune",
    area: "Nigdi",
    address: "9999 Nigdi Plaza, Nigdi, Pune 411044",
    propertyType: "flat",
    size: "3BHK",
    price: 25000,
    amenities: ["lift", "parking", "gym"],
    photos: [],
    rating: 4.1,
    reviews: 10,
    owner: "Pooja Sharma",
    contact: "+91-5432100018",
    nearbyPlaces: { hospital: 1.2, school: 1.3, airport: 20, mall: 1.6, railwayStation: 2.6, metroStation: 1.5 }
  },
  {
    id: 100,
    city: "Pune",
    area: "Pcmc",
    address: "10000 Municipal Tower, PCMC Area, Pune 411018",
    propertyType: "villa",
    size: "4BHK",
    price: 48000,
    amenities: ["swimming pool", "gym", "parking", "garden"],
    photos: [],
    rating: 4.3,
    reviews: 17,
    owner: "Ramesh Patel",
    contact: "+91-5432100019",
    nearbyPlaces: { hospital: 1.4, school: 1.5, airport: 23, mall: 1.9, railwayStation: 2.9, metroStation: 1.8 }
  }
];

export { PROPERTIES };
